
package proyecto.pkgfinal;

import javax.swing.JOptionPane;

/**
 *
 * @author koro
 */
public class main extends javax.swing.JFrame {

    static int hor = 0, min = 0, seg = 0, miliS = 0;

    //Thread cronometro = new Thread();
    public main() {
        initComponents();
jlbEquipo.setText(JOptionPane.showInputDialog("nombre del primer equipo"));
jlbEquipo1.setText(JOptionPane.showInputDialog("nombre del segundo equipo"));
        cronometro.start();

    }
    Thread cronometro = new Thread() {

        public void run() {
            //int hor = 0, min = 0, seg = 0, miliS = 0;
            for (;;) {//ciclo infinito para el cronometro/tiempo/reloj...
                try {
                    miliS++;
                    if (miliS > 99) {
                        miliS = 0;
                        seg++;
                    }
                    if (seg > 59) {
                        miliS = 0;
                        seg = 0;
                        min++;
                    }
                    //  if (min > 59) {
                    //      miliS = 0;
                    //      seg = 0;
                    //      min = 0;
                    //      hor++;
                    //  }
                    if (min == 1) {
                        JOptionPane.showMessageDialog(null, "fin del partido....");
                        cronometro.stop();
                    }
                    tiempo.setText(min + ":" + seg + ":" + miliS);

                    Thread.sleep(10);
                } catch (InterruptedException e) {

                }
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiempo = new javax.swing.JLabel();
        jlbEquipo1 = new javax.swing.JLabel();
        jlbEquipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tiempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tiempo.setText("0:0:0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jlbEquipo)
                .addGap(53, 53, 53)
                .addComponent(tiempo)
                .addGap(63, 63, 63)
                .addComponent(jlbEquipo1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo)
                    .addComponent(jlbEquipo1)
                    .addComponent(jlbEquipo))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbEquipo;
    private javax.swing.JLabel jlbEquipo1;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
